### ISSUE TITLE
Problem with JSON decoder

### ISSUE THREAD

**Issue by szhan** [szhan/game-on#1]
When running

"% python scripts/fetch_challenger_data.py -r NA1 -n 20"

it goes pretty well initially

"
INFO: Getting data for player 76379684
INFO: Getting data for player 37422723
INFO: Getting data for player 21276764
INFO: Getting data for player 22696988
INFO: Getting data for player 21836856
"

but then sometimes it runs into an error with JSON decoding...

"
Traceback (most recent call last):
  File "scripts/fetch_challenger_data.py", line 79, in <module>
    matches = json.loads(match_list_dto)["matches"]
  File "/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/anaconda/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 63 - line 1 column 245781 (char 62 - 245780)
"

Maybe there is a problem with character encoding... My understanding is that JSON decoder should automatically handle UTF-8. Riot API may return non-ASCII or non-UTF-8 characters in summoner names (unicode?), but it seems fine when downloading Korean summoner names...

**Comment by szhan** [comment]
It was not a problem with character encoding. It may be that the API sometimes returns invalid JSON strings. A try-catch workaround was implemented. If json.loads() encounters a decoding problem, then reattempt the API call, up to a user-specified number of times. The updated script now runs fine.
